# Generated by Django 3.0.2 on 2020-02-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='Timeloggedin',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
